import { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { AIGeneratedContent } from "@/components/common/AIGeneratedContent";

// NOTE: This is an enhanced version of the BusinessValuationCalculator component found in
// /src/components/calculators/BusinessValuationCalculator.tsx. This version is designed to work
// with the financial analysis page and uses the analyze-business-valuation Netlify function
// to generate AI-powered analysis and recommendations, whereas the original component
// performs calculations locally without making API calls.

interface BusinessValuationData {
  companyName: string;
  industry: string;
  revenue: number;
  netIncome: number;
  totalAssets: number;
  totalLiabilities: number;
  cashFlow: number;
  growthRate: number;
  discountRate: number;
}

interface BusinessValuationAnalysisProps {
  onSave?: (data: BusinessValuationData) => void;
}

export function BusinessValuationAnalysis({ onSave }: BusinessValuationAnalysisProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [analysisResult, setAnalysisResult] = useState<{ analysis: string; recommendations: string } | null>(null);
  
  const [formData, setFormData] = useState<BusinessValuationData>({
    companyName: '',
    industry: '',
    revenue: 0,
    netIncome: 0,
    totalAssets: 0,
    totalLiabilities: 0,
    cashFlow: 0,
    growthRate: 0,
    discountRate: 0.1
  });

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: name === 'companyName' || name === 'industry' ? value : parseFloat(value) || 0
    }));
  };

  const handleAnalyze = async () => {
    setLoading(true);
    setError(null);
    
    // Validate inputs
    if (!formData.companyName || !formData.industry) {
      setError("Please enter company name and industry.");
      setLoading(false);
      return;
    }
    
    try {
      const response = await fetch('/.netlify/functions/analyze-business-valuation', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
      
      if (!response.ok) {
        throw new Error(`Error: ${response.status} ${response.statusText}`);
      }
      
      const data = await response.json();
      setAnalysisResult(data);
      
      // Save the data if onSave is provided
      if (onSave) {
        onSave(formData);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "An unexpected error occurred");
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!analysisResult) return;
    
    const content = `# Business Valuation Analysis for ${formData.companyName}\n\n## Analysis\n${analysisResult.analysis}\n\n## Recommendations\n${analysisResult.recommendations}`;
    
    navigator.clipboard.writeText(content)
      .then(() => {
        console.log('Content copied to clipboard');
      })
      .catch(err => {
        console.error('Failed to copy content: ', err);
      });
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow || !analysisResult) return;

    const content = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Business Valuation Analysis - ${formData.companyName}</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }
          h1 { color: #2563eb; }
          h2 { color: #4b5563; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; }
          .section { margin-bottom: 30px; }
          .footer { margin-top: 40px; font-size: 12px; color: #6b7280; text-align: center; }
        </style>
      </head>
      <body>
        <h1>Business Valuation Analysis - ${formData.companyName}</h1>
        <div class="section">
          <h2>Analysis</h2>
          ${analysisResult.analysis.replace(/\n/g, '<br>')}
        </div>
        <div class="section">
          <h2>Recommendations</h2>
          ${analysisResult.recommendations.replace(/\n/g, '<br>')}
        </div>
        <div class="footer">
          Generated by Intellisync Business Suite on ${new Date().toLocaleDateString()}
        </div>
      </body>
      </html>
    `;

    printWindow.document.open();
    printWindow.document.write(content);
    printWindow.document.close();
    printWindow.print();
  };

  const resetForm = () => {
    setAnalysisResult(null);
    setError(null);
  };

  return (
    <div className="space-y-6">
      {!analysisResult ? (
        <Card>
          <CardHeader>
            <CardTitle>Business Valuation Analysis</CardTitle>
          </CardHeader>
          <CardContent>
            <form className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="companyName">Company Name</Label>
                  <Input
                    id="companyName"
                    name="companyName"
                    value={formData.companyName}
                    onChange={handleInputChange}
                    placeholder="Enter company name"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="industry">Industry</Label>
                  <Input
                    id="industry"
                    name="industry"
                    value={formData.industry}
                    onChange={handleInputChange}
                    placeholder="Enter industry"
                  />
                </div>
              </div>
              
              <Separator className="my-4" />
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="revenue">Annual Revenue ($)</Label>
                  <Input
                    id="revenue"
                    name="revenue"
                    type="number"
                    value={formData.revenue || ''}
                    onChange={handleInputChange}
                    placeholder="0"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="netIncome">Net Income ($)</Label>
                  <Input
                    id="netIncome"
                    name="netIncome"
                    type="number"
                    value={formData.netIncome || ''}
                    onChange={handleInputChange}
                    placeholder="0"
                  />
                </div>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="totalAssets">Total Assets ($)</Label>
                  <Input
                    id="totalAssets"
                    name="totalAssets"
                    type="number"
                    value={formData.totalAssets || ''}
                    onChange={handleInputChange}
                    placeholder="0"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="totalLiabilities">Total Liabilities ($)</Label>
                  <Input
                    id="totalLiabilities"
                    name="totalLiabilities"
                    type="number"
                    value={formData.totalLiabilities || ''}
                    onChange={handleInputChange}
                    placeholder="0"
                  />
                </div>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="cashFlow">Annual Cash Flow ($)</Label>
                  <Input
                    id="cashFlow"
                    name="cashFlow"
                    type="number"
                    value={formData.cashFlow || ''}
                    onChange={handleInputChange}
                    placeholder="0"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="growthRate">Growth Rate (%)</Label>
                  <Input
                    id="growthRate"
                    name="growthRate"
                    type="number"
                    value={formData.growthRate || ''}
                    onChange={handleInputChange}
                    placeholder="0"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="discountRate">Discount Rate (%)</Label>
                  <Input
                    id="discountRate"
                    name="discountRate"
                    type="number"
                    value={formData.discountRate || ''}
                    onChange={handleInputChange}
                    placeholder="10"
                  />
                </div>
              </div>
              
              <Button 
                type="button"
                onClick={handleAnalyze} 
                disabled={loading}
                className="w-full mt-4"
              >
                {loading ? "Analyzing..." : "Generate Valuation Analysis"}
              </Button>
              
              {error && (
                <p className="text-sm text-red-600 mt-2">{error}</p>
              )}
            </form>
          </CardContent>
        </Card>
      ) : (
        <>
          <AIGeneratedContent
            title={`Business Valuation Analysis - ${formData.companyName}`}
            description={`Industry: ${formData.industry}`}
            analysis={analysisResult.analysis}
            recommendations={analysisResult.recommendations}
            loading={loading}
            error={error || undefined}
            onCopy={handleCopy}
            onPrint={handlePrint}
          />
          
          <Button 
            variant="outline" 
            onClick={resetForm}
            className="mt-4"
          >
            Start New Analysis
          </Button>
        </>
      )}
    </div>
  );
}
